GET https://course-backend-1-ezqa.onrender.com/courses 

### 

POST https://course-backend-1-ezqa.onrender.com/courses 
Content-Type: application/json 

{
  "course_name": "React Js", 
  "professor": "Prof Nikhil",
  "start_date":"2024-04-20",
  "end_date": "2024-07-20" 

} 

### 

PUT https://course-backend-1-ezqa.onrender.com/courses/4
Content-Type: application/json 

{
    "course_name": "Node js",
    "professor": "MR Nikhil"
}

### 

DELETE https://course-backend-1-ezqa.onrender.com/courses/7

### 

GET https://course-backend-1-ezqa.onrender.com/assignments/1

### 

POST https://course-backend-1-ezqa.onrender.com/assignments 
Content-Type: application/json

{
    "course_id": 13,
    "title": "CSS Website",
    "due_date":"2024-02-30",
    "status":"completed"
}

### 

PUT https://course-backend-1-ezqa.onrender.com/assignments/1
Content-Type: application/json

{
    "title": "HTML Master",
    "due_date": "2024-02-29",
    "status": "pending"
}

### 

DELETE https://course-backend-1-ezqa.onrender.com/assignments/1